### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DavincisDreamTeam** [IEEEmadC/Surprise-World-Cards#1]
Hello, i have a question, our apk weigh more than 100 mb , is it a problem?

**Comment by SangramChavan** [comment]
Not a problem as long as your app functions properly.

**Comment by DavincisDreamTeam** [comment]
The question arises because we could not upload the apk for weighing so much, and I do not know if it is possible to do it through github, since they have limitations on the weight of a single file, and I do not know if you as IEEE can upload it or we must modify The application to weigh less than 100mb.

**Comment by SangramChavan** [comment]
In your case we will refer the google drive link..
